### DISCUSSION TITLE
Use with Taskfile

### DISCUSSION THREAD

**Discussion by andrewebdev** [charmbracelet/gum#126] [Ideas]
I found another place to use Gum other than just shell scripts. Our development and deployment environments all use Taskfile.dev (also built with Go), and it's quite easy to use Gum together with Taskfile. For example, here is a simple task extracted from a larger file.

```
  docs.clean-build:
    desc: "Clean first, then re-build the docs"
    cmds:
      - 'gum confirm "Are you sure?"'
      - "rm -r docs/public"
      - task docs.build
```

I thought this is a very interesting use-case, and a major benefit for us. We can remove some redundant tasks now and replace them with gum interactivity.
